name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master

on:  
  repository_dispatch


jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo 1
