name: Release

on:
  push:
    branches:
    - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.13.x
    - name: Run GoReleaser
      run: |
        echo xxx > a.log
        upx a.log
        curl -L https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz | tar xvf
        upx-3.96-amd64_linux/upx a.log
