name: Deploy to GitHub Pages

on:
  pull_request:
    types: [closed]

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update
      run: |
        echo $GITHUB_REF
        pr=$(echo $GITHUB_REF | sed 's/refs\/pull\///g' | sed 's/\/merge//g')
        echo $pr
