name: Deploy to GitHub Pages

on:
  push

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update
      run: |
        git clone https://github.com/LinuxSuRen/demo
        cd demo && touch def && git add . && hub commit -m 'Auto commit by bot' && hub push https://linuxsuren:${{ secrets.GITHUB_TOKEN }}@github.com/LinuxSuRen/demo.git
