name: Deploy to GitHub Pages

on:
  - push:
      branches:
      - master
  - repository_dispatch

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update
      run: echo 1
