name: Deploy to GitHub Pages

on:
  push

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update
      env:
        ABC: hao
      run: echo ${ABC}
