name: Deploy to GitHub Pages

on:
  push

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update
      run: |
        mkdir -p bin
        curl -L https://github.com/kevinburke/go-bindata/releases/download/v3.11.0/go-bindata-linux-amd64 -o bin/go-bindata
        chmod u+x bin/go-bindata
        echo $PATH
